### ISSUE TITLE
[ERROR] TypeError: Cannot read properties of undefined (reading 'secret')

### ISSUE THREAD

**Issue by jacknahid** [daniele77/aritester#6]
root@ip-172-31-94-168:/var/www/html/nahid/test2# fwconsole pm2 --log=callpanel
OUT > ==> /var/lib/asterisk/.pm2/logs/callpanel-error.log <==
[02.01.2024 17:34.34.174] [ERROR] TypeError: Cannot read properties of undefined (reading 'secret')
    at parseManagerConf (/var/www/html/admin/modules/callpanel/calls-contacts-panel/src/api/ami.ts:17:37)
    at /var/www/html/admin/modules/callpanel/calls-contacts-panel/src/api/ami.ts:28:25
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/admin/modules/callpanel/calls-contacts-panel/node_modules/tslib/tslib.js:114:62)
[02.01.2024 17:34.34.175] [ERROR] TypeError: Cannot read properties of undefined (reading 'secret')
    at parseManagerConf (/var/www/html/admin/modules/callpanel/calls-contacts-panel/src/api/ami.ts:17:37)
    at /var/www/html/admin/modules/callpanel/calls-contacts-panel/src/api/ami.ts:28:25
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/admin/modules/callpanel/calls-contacts-panel/node_modules/tslib/tslib.js:114:62)

==> /var/lib/asterisk/.pm2/logs/callpanel-out.log <==
  serviceInstallFile: '/lib/systemd/system/fpbx-call-panel.service',
  frontendBuildDir: '/var/www/html/admin/modules/callpanel/calls-contacts-panel/frontend/build/',
  activeCallsCheckIntervalMs: 1000,
  callerIdPrefixes: [ '+' ],
  callerIdResolveLength: 6,
  callLogsCheckIntervalMs: 3000,
  httpPort: 4848,
  phonebookCheckIntervalMs: 180000
}
[02.01.2024 17:34.34.139] [LOG]   running as service

**Comment by daniele77** [comment]
Can you please give us some context?
